# Generated by Django 4.1.3 on 2022-12-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersDefinedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=45)),
                ('word_definition', models.CharField(max_length=500)),
                ('word_pronounciation', models.CharField(max_length=150)),
                ('word_etymology', models.CharField(max_length=500)),
                ('word_origin_date', models.CharField(max_length=150)),
            ],
        ),
    ]
